<a href="https://colab.research.google.com/github/jorgealbertogomezgomez77/tensorflow_2.0/blob/master/Colab_2_Introducci%C3%B3n_a_TensorFlow_2_0_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## TensorFlow 1.X

### Instalar TensorFlow 1.X



In [0]:
!pip install tensorflow-gpu==1.13.1

     |████████████████████████████████| 345.2MB 62kB/s 
     |████████████████████████████████| 3.2MB 30.1MB/s 
     |████████████████████████████████| 368kB 45.5MB/s 
ERROR: tensorflow 1.14.0 has requirement tensorboard<1.15.0,>=1.14.0, but you'll have tensorboard 1.13.1 which is incompatible.
ERROR: tensorflow 1.14.0 has requirement tensorflow-estimator<1.15.0rc0,>=1.14.0rc0, but you'll have tensorflow-estimator 1.13.0 which is incompatible.
  Found existing installation: tensorboard 1.14.0
    Uninstalling tensorboard-1.14.0:
      Successfully uninstalled tensorboard-1.14.0
  Found existing installation: tensorflow-estimator 1.14.0
    Uninstalling tensorflow-estimator-1.14.0:
      Successfully uninstalled tensorflow-estimator-1.14.0


In [0]:
import tensorflow as tf

In [0]:
tf.__version__

'1.13.1'

### Constantes

#### Definir una constante

In [0]:
# Definir una constante en TensorFlow
tensor = tf.constant([[23, 4], [32, 51]])

In [0]:
tensor

<tf.Tensor 'Const:0' shape=(2, 2) dtype=int32>

In [0]:
# Si la session no ha sido inicializada, no se pueden acceder a los valores de la constante
tensor.eval()

ValueError: ignored

#### Consultar los valores de la constante

In [0]:
session = tf.Session()

In [0]:
session.run(tf.global_variables_initializer())

In [0]:
tensor_value = session.run(tensor)

In [0]:
tensor_value

array([[23,  4],
       [32, 51]], dtype=int32)

### Variables

#### Definir una variable

In [0]:
# Definir una variable de TensorFlow 
variable = tf.Variable([[30, 20], [10, 45]])

Instructions for updating:
Colocations handled automatically by placer.


In [0]:
variable

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32_ref>

In [0]:
# Si la session no ha sido inicializada, no se podrán acceder a los valores de la variable
variable.eval()

NameError: ignored

#### Consultar los valores de una variable

In [0]:
# Inicializar una session
session = tf.Session()

In [0]:
# Inicializar TODAS las variables de la session
session.run(tf.global_variables_initializer())

In [0]:
# Ejecutar el método eval en el entorno con la sesión iniciada para recuperar los valores del mismo
variable.eval(session)

NameError: ignored

## TensorFlow 2.0

### Instalar TensorFlow 2.0

In [0]:
!pip install tensorflow-gpu==2.0.0-alpha0

     |████████████████████████████████| 332.1MB 55kB/s 
     |████████████████████████████████| 419kB 40.5MB/s 
     |████████████████████████████████| 3.0MB 28.7MB/s 
  Found existing installation: tensorflow-gpu 1.13.1
    Uninstalling tensorflow-gpu-1.13.1:
      Successfully uninstalled tensorflow-gpu-1.13.1


In [0]:
import tensorflow as tf
import numpy as np

In [0]:
tf.__version__

'2.0.0-alpha0'

### Constantes

#### Definir una constante

In [0]:
# Definir una constante en TensorFlow 2.0
tensor_20 = tf.constant([[23, 4], [32, 51]])

In [0]:
tensor_20

<tf.Tensor: id=0, shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [32, 51]], dtype=int32)>

In [0]:
# Obtener el tamaño de un tensor
tensor_20.shape

TensorShape([2, 2])

#### Consultar los valores de una constante

In [0]:
# Obtener los valores directamente desde una constante de TensorFlow con numpy, sin necesidad de una session
tensor_20.numpy()

array([[23,  4],
       [32, 51]], dtype=int32)

In [0]:
# Podemos convertir un array de numpy a un tensor de TensorFlow directamente
numpy_tensor = np.array([[23,  4], [32, 51]])

In [0]:
tensor_from_numpy = tf.constant(numpy_tensor)

In [0]:
tensor_from_numpy

<tf.Tensor: id=3, shape=(2, 2), dtype=int64, numpy=
array([[23,  4],
       [32, 51]])>

### Variables

#### Definir una variable

In [0]:
tf2_variable = tf.Variable([[1., 2., 3.], [4., 5., 6.]])
tf2_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

#### Consultar los valores de una variable

In [0]:
tf2_variable.numpy()

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

#### Cambiar un valor especifico de una variable

In [0]:
tf2_variable[0, 2].assign(100)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[  1.,   2., 100.],
       [  4.,   5.,   6.]], dtype=float32)>

In [0]:
tf2_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[  1.,   2., 100.],
       [  4.,   5.,   6.]], dtype=float32)>

### Operaciones con tensores

In [0]:
tensor = tf.constant([[1, 2], [3, 4]])
tensor

<tf.Tensor: id=27, shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

#### Sumar un escalar a un tensor

In [0]:
tensor + 2

<tf.Tensor: id=30, shape=(2, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6]], dtype=int32)>

#### Multiplicar un escalar por un tensor

In [0]:
tensor * 5

<tf.Tensor: id=33, shape=(2, 2), dtype=int32, numpy=
array([[ 5, 10],
       [15, 20]], dtype=int32)>

#### Utilizar funciones de Numpy sobre tensores de TensorFlow

In [0]:
# Obtener los cuadrados de todos los números de un tensor de TensorFlow
np.square(tensor)

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [0]:
# Obtener la raíz cuadrada de todos los números de un tensor de TensorFlow
np.sqrt(tensor)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

#### Producto escalar entre dos tensores

In [0]:
 np.dot(tensor, tensor_20)

array([[ 87, 106],
       [197, 216]], dtype=int32)

### Strings en TensorFlow 2.0

In [0]:
tf_string = tf.constant("TensorFlow")
tf_string

<tf.Tensor: id=41, shape=(), dtype=string, numpy=b'TensorFlow'>

#### Operaciones simples con strings

In [0]:
tf.strings.length(tf_string)

<tf.Tensor: id=43, shape=(), dtype=int32, numpy=10>

In [0]:
tf.strings.unicode_decode(tf_string, "UTF8")

<tf.Tensor: id=48, shape=(10,), dtype=int32, numpy=array([ 84, 101, 110, 115, 111, 114,  70, 108, 111, 119], dtype=int32)>

#### Almacenar arrays de strings

In [0]:
tf_string_array = tf.constant(["TensorFlow", "Deep Learning", "AI"])

In [0]:
# Iterar sobre un array de strings en TF
for string in tf_string_array:
  print(string)

tf.Tensor(b'TensorFlow', shape=(), dtype=string)
tf.Tensor(b'Deep Learning', shape=(), dtype=string)
tf.Tensor(b'AI', shape=(), dtype=string)
